apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-deploy-prod
bases:
  - ../../base
namespace: k8s-deploy-prod
images:
- name: quay.io/redhattraining/hello-world-nginx
  newName: quay.io/redhattraining/versioned-hello
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: hello
  path: hostnamePatch.yaml
